version: 4.0.69
steps:
  - prompt: Click on "Cookies Settings".
    commands:
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Click on "Cookies Settings".
    commands:
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Click on "Cookies Settings".
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Click on "Cookies Settings".
    commands:
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Click on "Cookies Settings".
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Click on "Cookies Settings".
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Click on "Cookies Settings".
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
      - command: focus-application
        name: Google Chrome
  - prompt: Adjust settings.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Adjust settings.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Adjust settings.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
  - prompt: Adjust settings.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
      - command: wait
        timeout: 2000
      - command: hover-text
        text: Save Settings
        description: button to save cookie preferences
        action: click
  - prompt: Adjust settings.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Save Settings
        description: button to save cookie preferences
        action: click
  - prompt: Adjust settings.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
      - command: hover-text
        text: Save Settings
        description: button to save cookie preferences
        action: click
      - command: hover-text
        text: Save Settings
        description: button to save cookie preferences
        action: click
  - prompt: Save changes.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Save Settings
        description: button to save cookie preferences
        action: click
  - prompt: Save changes.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Save Settings
        description: button to save cookie preferences
        action: click
  - prompt: Save changes.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Accept Cookies
        description: button to accept cookie preferences
        action: click
  - prompt: Save changes.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Cookies Settings
        description: link in the cookie consent banner
        action: click
      - command: hover-text
        text: Save Settings
        description: button to save cookie preferences
        action: click
  - prompt: Save changes.
    commands:
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Accept Cookies
        description: button to accept cookie preferences
        action: click
      - command: focus-application
        name: Google Chrome
      - command: hover-text
        text: Accept Cookies
        description: button to accept cookie preferences
        action: click
  - prompt: >-
      Assert that the changes are applied and a confirmation message is shown. 
      # Use the content of the file from the environment
    commands:
      - command: focus-application
        name: Google Chrome
      - command: assert
        expect: confirmation message is visible
